logger:
    console:
        level: DEBUG

cognite:
    # Read these from environment variables
    host: ${COGNITE_BASE_URL}
    project: ${COGNITE_PROJECT}

    idp-authentication:
        token-url: ${COGNITE_TOKEN_URL}

        client-id: ${COGNITE_CLIENT_ID}
        secret: ${COGNITE_CLIENT_SECRET}
        scopes:
            - ${COGNITE_BASE_URL}/.default
    external-id-prefix: "frost:"
    extraction-pipeline:
        external-id: "met-pipeline"
    data-set-id: 357629980950767

frost:
    client-id: ${FROST_CLIENT_ID}
    elements:
      - wind_speed
      - air_temperature
      - air_pressure_at_sea_level

extractor:
    create-assets: false

backfill:
    backfill-to: "2021-01-01"

locations:
  # Blindern
  - station_id: "SN18700"

  # UiB
  - station_id: "SN50539"