logger:
    console:
        level: INFO

cognite:
    # Read these from environment variables
    host: ${COGNITE_BASE_URL}
    project: ${COGNITE_PROJECT}

    idp-authentication:
        token-url: ${COGNITE_TOKEN_URL}

        client-id: ${COGNITE_CLIENT_ID}
        secret: ${COGNITE_CLIENT_SECRET}
        scopes:
            - ${COGNITE_BASE_URL}/.default
    external-id-prefix: "tempest:"
    extraction-pipeline:
        external-id: "met-pipeline"
    data-set-id: 357629980950767

tempest:
    token: ${TEMPEST_TOKEN}
    device_id: ${TEMPEST_DEVICE_ID}
    device_name: ${TEMPEST_DEVICE_NAME}
    elements:
      - pressure
      - wind_avg

extractor:
    create-assets: false
    upload_interval: 20
    parallelism: 10
    collector_interval: 10

backfill:
    backfill-to: "2021-01-01"